remaped = {
    'Frankfurt':'FRA',
    'Frankfurt am Main':'FRA',
    'Basel':'BSL',
    'Amsterdam':'AMS',
    'Amsterdam Airport Schiphol':'AMS',
    'Brussels':'BRU',
    'Zurich':'ZRH',
    'Zurich Airport':'ZRH',
    'Dubai':'DXB',
    'Dubai International Airport':'DXB',
    'Hyderabad':'HYD',
    'Begumpet Airport':'HYD',
    'Shanghai Pu Dong':'PVG',
    'Shanghai Pudong International Airport':'PVG',
    'Singapore':'SIN',
    'Singapore Changi Airport':'SIN',
    'Hongkong':'HKG',
    'Hong Kong International Airport':'HKG',
    'Tokyo Narita':'NRT',
    'Narita International Airport':'NRT',
    'San Francisco':'BSL',
    'San Francisco International Airport':'BSL',
    'Chicago':'ORD',
    "Chicago O'Hare International Airport":'ORD',
    'Sydney':'SYD',
    'Sydney Airport':'SYD',
    'Santiogo de Chili':'SCL',
    'Comodoro Arturo Merino Benítez International Airport':'SCL',
    'Johannesburg':'JNB',
    'O.R. Tambo International Airport':'JNB',
    'Lima':'LIM',
    'Jorge Chávez International Airport':'LIM'
}
